version: '3'

services:
  node-express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data 
    environment:
      NODE_ENV: production